version: '3'

networks:
    nginx-php74-mysql8-node-elk:

services:

    # nginx
    nginx-service:
        image: nginx:stable-alpine
        container_name: nginx-container
        ports:
            - ${LOCAL_NGINX_PORT}:80
        volumes:
            - ./app:/var/www/project
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./logs/nginx/:/var/log/nginx
        depends_on:
            - php74-service
            - mysql8-service
        networks:
            - nginx-php74-mysql8-node-elk

    # php
    php74-service:
        build:
            context: .
            args:
                TIMEZONE: ${TIMEZONE}
            dockerfile: ./php/Dockerfile
        container_name: php74-container
        ports:
            - ${LOCAL_PHP_PORT}:9000
        volumes:
            - ${SYMFONY_APP_PATH}:/var/www/project
            - ./logs/app:/var/www/project/var/logs
            - ./key/ssh/id_rsa:/root/.ssh/id_rsa:ro
        networks:
            - nginx-php74-mysql8-node-elk
        environment:
            - SSH_AUTH_SOCK

    # mysql
    mysql8-service:
        image: mysql:8
        container_name: mysql8-container
        ports:
            - ${LOCAL_MYSQL_PORT}:3306
        volumes:
            - ".data/db:/var/lib/mysql"
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        restart: always # always restart unless stopped manually
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        networks:
            - nginx-php74-mysql8-node-elk

    # node
    node-service:
        image: node:latest
        container_name: node-container
        volumes:
            - ./app:/var/www/project
        working_dir: /var/www/project
        networks:
            - nginx-php74-mysql8-node-elk

    # elasticsearch logstash kibana
    elk-service:
        image: willdurand/elk
        ports:
            - ${LOCAL_LOGSTASH_PORT}:80
        volumes:
            - ./elk/logstash:/etc/logstash
            - ./elk/logstash/patterns:/opt/logstash/patterns
        networks:
            - nginx-php74-mysql8-node-elk
        container_name: elk-container
